version: '3'

services:
  nextjs:
    image: yt2mp3_prod
    container_name: yt2mp3_prod
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/app
    ports:
      - 4242:4242
    restart: always
