version: '3'

services:
  yt2mp3:
#    image: yt2mp3
    image: busshi/yt2mp3:latest
#    container_name: yt2mp3
 #   build:
  #    context: ./
   #   dockerfile: Dockerfile
    volumes:
      - ./app:/usr/app
    ports:
      - 80:80
    restart: unless-stopped
