version: '3'

services:
  nextjs:
    image: yt2mp3
    container_name: yt2mp3
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/app
    ports:
      - 80:80
    restart: unless-stopped