version: '3'

services:
  nextjs:
    image: yt2mp3_dev
    container_name: yt2mp3_dev
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/usr/app
    ports:
      - 4242:4242
    restart: always
